05 lection3 04 template
js-tasks-ru/htmlcss-20211021_mjaffk pull request #12
Opened 2021-11-06 11:49 UTC by mjaffk

2021-11-06 11:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-06 13:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-06 14:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-06 14:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-06 20:09 UTC, GSemikozov requested changes

2021-11-06 20:09 UTC, GSemikozov commented on components/navigation-menu/navigation-menu.css
> +    margin: 0 56px 0 auto;
на уровне блока марджины не задаем

2021-11-06 20:09 UTC, GSemikozov commented on components/side-bar/side-bar.css
> +    margin: 0;
несколько мест где встречаю подобный сброс - может унести в глобальные сбросы?

2021-11-06 20:09 UTC, GSemikozov commented on components/side-bar/side-bar.css
> +    margin: 0;
марджин + паддинг 0

2021-11-06 20:09 UTC, GSemikozov commented on components/template/template.css
> +    background: #E5E5E5;
здесь и ниже лучше все-таки использовать переменную - скоро это. нам пригодится

2021-11-06 20:21 UTC, mjaffk commented on components/navigation-menu/navigation-menu.css
> +    margin: 0 56px 0 auto;
Done

2021-11-06 20:29 UTC, mjaffk commented on components/side-bar/side-bar.css
> +    margin: 0;
Done

2021-11-06 20:42 UTC, mjaffk commented on components/template/template.css
> +    background: #E5E5E5;
Done

2021-11-06 20:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-06 20:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-07 12:07 UTC, GSemikozov approved these changes

2021-11-07 12:07 UTC, merged