Add solution for task 06-lection4_06 SVG Sprite
js-tasks-ru/htmlcss-20211021_mjaffk pull request #17
Opened 2021-11-14 15:15 UTC by mjaffk

2021-11-14 15:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-14 15:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-14 18:56 UTC, GSemikozov requested changes

2021-11-14 18:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    content: url("../../assets/images/icons.svg#arrow-bottom");
если добавляем иконку через css - тогда нужно подключать иконку отдельно (свг спрайт работать не будет)

2021-11-14 18:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    content: url("../../assets/images/icons.svg#arrow-top");
чтобы при этом не подключать еще одну иконку - лучше уже подключенную просто повернуть через css как предложено в описании к задаче

2021-11-15 16:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-15 16:48 UTC, mjaffk commented on 03-lection1/02-accordion/accordion.css
> +    content: url("../../assets/images/icons.svg#arrow-top");
Done

2021-11-15 16:48 UTC, mjaffk commented on 03-lection1/02-accordion/accordion.css
> +    content: url("../../assets/images/icons.svg#arrow-bottom");
Done

2021-11-17 14:11 UTC, GSemikozov approved these changes

2021-11-17 14:11 UTC, merged