Add solution for task 03_01 Button
js-tasks-ru/htmlcss-20211021_mjaffk pull request #3
Opened 2021-10-29 19:38 UTC by mjaffk

2021-10-29 19:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-29 20:23 UTC, GSemikozov requested changes

2021-10-29 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-family: inherit;
лучше указать явно (наследоваться можно от блоков с разным font-family, что конечно же будет нехорошо)

2021-10-29 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 100%;
16px (100% -  будем наследовать от родителя, но у кнопки всегда должен быть один сайз)

2021-10-29 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 0;
марджины на уровне блока в любом случае не задаем

2021-10-29 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14px;
по краям лучше все-таки тоже добавить паддинги (например 15 px), иначе длинный текст будет прилипать к краям

2021-10-29 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__text {
можно сразу определить на уровне .button

2021-10-29 20:31 UTC, mjaffk commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14px;
Я согласна, но в дизайне так и не поняла, как его считать, поэтому оставила пустым, чтоб разобраться с этим вопросом.

2021-10-29 20:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-30 14:25 UTC, mjaffk commented on 03-lection1/01-button/button.css
> +    font-family: inherit;
Поправила

2021-10-30 14:25 UTC, mjaffk commented on 03-lection1/01-button/button.css
> +    font-size: 100%;
Done

2021-10-30 14:26 UTC, mjaffk commented on 03-lection1/01-button/button.css
> +    margin: 0;
Done

2021-10-30 14:26 UTC, mjaffk commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14px;
Done

2021-10-30 14:26 UTC, mjaffk commented on 03-lection1/01-button/button.css
> +.button__text {
Done

2021-10-31 08:01 UTC, GSemikozov approved these changes

2021-10-31 08:01 UTC, merged